export const universita = [
  "Universita di Bologna",
  "Universita La Sapienza di Roma",
  "Universita di Milano",
  "Universita di Milano Bicocca",
  "Politecnico di Milano",
  "Politecnico di Torino",
  "Universita di Torino",
  "Universita di Padova",
  "Universita di Bari",
  "Universita di Napoli Federico II",
  "Universita di Firenze",
  "Universita di Pisa",
  "Universita di Genova",
  "Universita di Palermo",
  "Universita di Catania",
  "Universita di Verona",
  "Universita di Trento",
  "Universita di Trieste",
  "Universita di Parma",
  "Universita di Modena e Reggio Emilia",
  "Universita di Ferrara",
  "Universita di Siena",
  "Universita di Perugia",
  "Universita di Cagliari",
  "Universita di Sassari",
  "Universita della Calabria",
  "Universita di Salerno",
  "Universita di Bergamo",
  "Universita di Brescia",
  "Universita Cattolica del Sacro Cuore",
  "Universita Bocconi",
  "LUISS Guido Carli",
  "Universita Roma Tre",
  "Universita Roma Tor Vergata",
  "Universita degli Studi dell'Insubria",
  "Universita di Udine",
  "Universita della Tuscia",
  "Universita del Molise",
  "Universita di Camerino",
  "Universita Politecnica delle Marche",
  "Universita di Urbino",
  "Universita di L'Aquila",
  "Universita di Foggia",
  "Universita del Salento",
  "Universita Magna Graecia di Catanzaro",
  "Universita Mediterranea di Reggio Calabria",
  "Universita Kore di Enna",
  "Universita di Messina",
  "Universita Vita-Salute San Raffaele",
  "Politecnico di Bari",
  "IULM Milano",
  "Universita di Pavia",
  "Universita Carlo Cattaneo LIUC",
  "Universita Ca Foscari Venezia",
  "Universita IUAV di Venezia",
  "Harvard University",
  "Stanford University",
  "MIT",
  "University of Oxford",
  "University of Cambridge",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of California Berkeley",
  "ETH Zurich",
  "Imperial College London",
  "University College London",
  "Sorbonne Universite",
  "Technical University of Munich",
  "LMU Munich",
  "University of Toronto",
  "McGill University",
  "Australian National University",
  "University of Melbourne",
  "National University of Singapore",
  "Tsinghua University",
  "Peking University",
  "University of Tokyo"
]

export const materie = [
  "Analisi Matematica 1",
  "Analisi Matematica 2",
  "Algebra Lineare",
  "Geometria",
  "Analisi Numerica",
  "Probabilita e Statistica",
  "Statistica",
  "Statistica Medica",
  "Ricerca Operativa",
  "Logica Matematica",
  "Fisica Generale 1",
  "Fisica Generale 2",
  "Fisica Tecnica",
  "Chimica Generale",
  "Chimica Organica",
  "Chimica Analitica",
  "Chimica Fisica",
  "Biologia Generale",
  "Biologia Molecolare",
  "Biochimica",
  "Genetica",
  "Microbiologia",
  "Anatomia Umana",
  "Fisiologia",
  "Istologia",
  "Patologia Generale",
  "Farmacologia",
  "Immunologia",
  "Programmazione 1",
  "Programmazione 2",
  "Programmazione Orientata agli Oggetti",
  "Basi di Dati",
  "Algoritmi e Strutture Dati",
  "Reti di Calcolatori",
  "Sistemi Operativi",
  "Architettura degli Elaboratori",
  "Ingegneria del Software",
  "Intelligenza Artificiale",
  "Machine Learning",
  "Sicurezza Informatica",
  "Sistemi Distribuiti",
  "Calcolo Numerico",
  "Elettrotecnica",
  "Elettronica Analogica",
  "Elettronica Digitale",
  "Telecomunicazioni",
  "Automatica",
  "Controlli Automatici",
  "Meccanica Razionale",
  "Meccanica Applicata",
  "Scienza delle Costruzioni",
  "Tecnica delle Costruzioni",
  "Termodinamica Applicata",
  "Fluidodinamica",
  "Disegno Tecnico Industriale",
  "Disegno di Macchine",
  "Macchine a Fluido",
  "Impianti Industriali",
  "Tecnologia Meccanica",
  "Idraulica",
  "Topografia",
  "Urbanistica",
  "Geotecnica",
  "Materiali da Costruzione",
  "Storia dell'Architettura",
  "Progettazione Architettonica",
  "Composizione Architettonica",
  "Diritto Privato",
  "Diritto Costituzionale",
  "Diritto Penale",
  "Diritto Civile",
  "Diritto Commerciale",
  "Diritto Internazionale",
  "Diritto Amministrativo",
  "Diritto del Lavoro",
  "Diritto Tributario",
  "Diritto Romano",
  "Filosofia del Diritto",
  "Storia del Diritto",
  "Procedura Civile",
  "Procedura Penale",
  "Economia Politica",
  "Microeconomia",
  "Macroeconomia",
  "Economia Aziendale",
  "Economia degli Intermediari Finanziari",
  "Ragioneria Generale",
  "Contabilita e Bilancio",
  "Finanza Aziendale",
  "Marketing",
  "Organizzazione Aziendale",
  "Strategia d'Impresa",
  "Statistica Economica",
  "Econometria",
  "Storia Economica",
  "Politica Economica",
  "Scienze delle Finanze",
  "Psicologia Generale",
  "Psicologia dello Sviluppo",
  "Psicologia Sociale",
  "Psicologia Clinica",
  "Psicometria",
  "Neuropsicologia",
  "Pedagogia Generale",
  "Didattica Generale",
  "Sociologia Generale",
  "Antropologia Culturale",
  "Filosofia Teoretica",
  "Storia della Filosofia",
  "Filosofia Morale",
  "Estetica",
  "Logica",
  "Storia Contemporanea",
  "Storia Medievale",
  "Storia Moderna",
  "Storia Romana",
  "Storia Greca",
  "Letteratura Italiana",
  "Letteratura Inglese",
  "Letteratura Francese",
  "Letteratura Spagnola",
  "Letteratura Tedesca",
  "Linguistica Generale",
  "Glottologia",
  "Scienze della Comunicazione",
  "Sociologia della Comunicazione",
  "Teoria e Tecniche dei Media",
  "Scienze Motorie",
  "Anatomia Funzionale",
  "Fisiologia dell'Esercizio",
  "Teoria e Metodologia dell'Allenamento",
  "Scienze Infermieristiche",
  "Fisioterapia",
  "Scienze Politiche",
  "Relazioni Internazionali",
  "Geografia Politica",
  "Storia delle Relazioni Internazionali",
  "Diritto dell'Unione Europea",
  "Scienze Ambientali",
  "Ecologia",
  "Geologia Generale",
  "Mineralogia",
  "Petrografia",
  "Biotecnologie",
  "Bioinformatica",
  "Veterinaria Generale",
  "Patologia Veterinaria",
  "Odontoiatria Conservativa",
  "Farmacia Generale",
  "Tecnologia Farmaceutica",
  "Chimica Farmaceutica"
]
