export const universita: string[] = [
  'Università degli Studi di Bologna',
  'Università degli Studi di Milano',
  'Università degli Studi di Roma La Sapienza',
  'Politecnico di Milano',
  'Politecnico di Torino',
  'Università degli Studi di Napoli Federico II',
  'Università degli Studi di Torino',
  'Università degli Studi di Padova',
  'Università degli Studi di Firenze',
  'Università degli Studi di Pisa',
  'Università degli Studi di Roma Tor Vergata',
  'Università degli Studi di Roma Tre',
  'Università degli Studi di Genova',
  'Università degli Studi di Bari Aldo Moro',
  'Università degli Studi di Catania',
  'Università degli Studi di Palermo',
  'Università degli Studi di Trieste',
  'Università degli Studi di Trento',
  'Università degli Studi di Verona',
  'Università degli Studi di Brescia',
  'Università degli Studi di Modena e Reggio Emilia',
  'Università degli Studi di Parma',
  'Università degli Studi di Ferrara',
  'Università degli Studi di Siena',
  'Università degli Studi di Perugia',
  'Università degli Studi di Ancona (Politecnica delle Marche)',
  'Università degli Studi di Cagliari',
  'Università degli Studi di Sassari',
  'Università degli Studi di Messina',
  'Università degli Studi di Catanzaro',
  'Università degli Studi di Salerno',
  'Università degli Studi di Cassino',
  'Università degli Studi di Foggia',
  'Università degli Studi di Lecce (Salento)',
  'Università degli Studi di Bari (LUM)',
  'Università degli Studi di Udine',
  'Università degli Studi del Piemonte Orientale',
  'Università degli Studi della Valle d\'Aosta',
  'Università degli Studi di Bergamo',
  'Università degli Studi di Pavia',
  'Università Commerciale Luigi Bocconi',
  'Università Cattolica del Sacro Cuore',
  'LUISS Guido Carli',
  'Università IULM',
  'Università Vita-Salute San Raffaele',
  'Università degli Studi di Milano-Bicocca',
  'Libera Università di Bolzano',
  'SISSA - Scuola Internazionale Superiore di Studi Avanzati',
  'Scuola Normale Superiore di Pisa',
  'Scuola Sant\'Anna di Pisa',
  'IMT Scuola Alti Studi Lucca',
  'Harvard University',
  'MIT - Massachusetts Institute of Technology',
  'Stanford University',
  'Oxford University',
  'Cambridge University',
  'ETH Zurich',
  'École Polytechnique',
  'Sorbonne Université',
  'TU Munich',
  'UCL - University College London',
]

export const materie: string[] = [
  'Analisi Matematica',
  'Analisi Matematica 1',
  'Analisi Matematica 2',
  'Algebra Lineare',
  'Geometria',
  'Fisica 1',
  'Fisica 2',
  'Chimica Generale',
  'Chimica Organica',
  'Biologia',
  'Biologia Molecolare',
  'Informatica',
  'Programmazione',
  'Algoritmi e Strutture Dati',
  'Basi di Dati',
  'Reti di Calcolatori',
  'Sistemi Operativi',
  'Intelligenza Artificiale',
  'Machine Learning',
  'Ingegneria del Software',
  'Economia Aziendale',
  'Macroeconomia',
  'Microeconomia',
  'Statistica',
  'Econometria',
  'Marketing',
  'Diritto Privato',
  'Diritto Pubblico',
  'Diritto Commerciale',
  'Diritto del Lavoro',
  'Diritto Penale',
  'Diritto Internazionale',
  'Storia del Diritto',
  'Filosofia',
  'Storia della Filosofia',
  'Logica',
  'Etica',
  'Storia',
  'Storia Moderna',
  'Storia Contemporanea',
  'Storia dell\'Arte',
  'Letteratura Italiana',
  'Letteratura Inglese',
  'Letteratura Francese',
  'Letteratura Tedesca',
  'Linguistica',
  'Lingua Inglese',
  'Lingua Francese',
  'Lingua Tedesca',
  'Lingua Spagnola',
  'Lingua Cinese',
  'Psicologia Generale',
  'Psicologia Cognitiva',
  'Psicologia Clinica',
  'Psicologia dello Sviluppo',
  'Sociologia',
  'Antropologia',
  'Pedagogia',
  'Medicina Interna',
  'Anatomia',
  'Fisiologia',
  'Patologia',
  'Farmacologia',
  'Chirurgia',
  'Architettura',
  'Urbanistica',
  'Disegno Tecnico',
  'Scienza delle Costruzioni',
  'Topografia',
  'Elettrotecnica',
  'Elettronica',
  'Telecomunicazioni',
  'Automazione',
  'Meccanica',
  'Termodinamica',
  'Fluidodinamica',
  'Geologia',
  'Geotecnica',
  'Contabilità',
  'Ragioneria',
  'Finanza Aziendale',
  'Matematica Finanziaria',
  'Business Administration',
  'Management',
]
